version: '3.9'

services:
  api:
    container_name: php_v21_0_5
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    depends_on:
      - rabbitmq
    volumes:
      - ./api:/var/www/symfony:cached
      - ./api/logs/symfony:/var/www/symfony/var/log:cached
    networks:
      - symfony

  nginx:
    container_name: nginx_v21_0_5
    build: docker/nginx
    restart: on-failure
    volumes:
      - ./api:/var/www/api:delegated
      - ./api/var/logs/nginx/:/var/log/nginx:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ui.conf:/etc/nginx/conf.d/ui.conf:delegated
      - ./api:/var/www/symfony
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - api
      - rabbitmq
    networks:
      - symfony

  ui:
    container_name: react_v21_0_5
    build: ./ui
    restart: on-failure
    command: "npm start"
    depends_on:
      - api
    networks:
      - symfony
    volumes:
      - ./ui:/var/www/ui:delegated
      - nodemodules:/var/www/ui/node_modules
    ports:
      - '${REACT_PORT}:3000'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_v21_0_5
    hostname: localhost
    volumes:
      - rmqconf:/etc/rabbitmq
      - rmqdata:/var/lib/rabbitmq/mnesia
      - rmqlogs:/var/log/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "${RABBITMQ_MANAGER_PORT}:15672"
      - "${RABBITMQ_PORT}:5672"
    networks:
      - symfony
  
  mailhog:
    container_name: mailhog_v21_0_5
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - '${MAILER_SANDBOX_PORT}:8025'
      - '${MAILER_DSN_PORT}:1025'
    networks:
      - symfony

volumes:
  nodemodules: {}
  rmqconf:
    driver: local
  rmqlogs:
    driver: local
  rmqdata:
    driver: local

networks:
  symfony:
    driver: bridge
