version: '3.9'

services:
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
    networks:
      - symfony

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony
  
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - '${MAILER_SANDBOX_PORT}:8025'
      - '${MAILER_DSN_PORT}:1025'
    networks:
      - symfony

networks:
  symfony:
