# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
  
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]
    
  App\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
  
  app.dto.serializer:
    class: 'App\Service\Serializer\DTOSerializer'
    
  App\Service\ExternalRequest\RequestBuilder:
    calls:
      - setClient: [ '@http_client' ]
      
  App\Service\HistoricalData\HistoricalDataService:
    arguments:
      $dataLink: "%env(historical_data_link)%"

  App\Service\Symbol\SymbolService:
    arguments:
      $dataLink: "%env(symbols_list_link)%"

  Symfony\Component\Serializer\SerializerInterface $dtoSerializer: '@app.dto.serializer'
  
  App\Service\PriceList\PriceListInterface: '@App\Service\PriceList\PriceListService'
  App\Service\PriceList\PriceListInterface $priceListNotify: '@App\Service\PriceList\PriceListNotification'
  
  Symfony\Component\Mime\Email: ~
